version: "3.7"

services:
  traking_service:
    
    restart: always
    container_name: traking_service
    build:
      context: .
      dockerfile: "./docker/${ENVIRONMENT}/dockerfile"
    volumes:
      - .:/app
      - /app/node_modules

networks:
  defalt:
    driver: bridge