version: "3.7"

services:
  traking_service:
    restart: always
    container_name: traking_service
    ports:
      - "3003:3003"
    build:
      context: .
      dockerfile: "./docker/${ENVIRONMENT}/dockerfile"
    volumes:
      - .:/app
      - /app/node_modules

