FROM node:alpine

WORKDIR app

COPY ../../package.json .

COPY ../../yarn.lock .

RUN yarn install

RUN yarn global add pm2

COPY ../../. .

RUN npx prisma generate

RUN yarn build

VOLUME ["/app/dist"]

CMD ["pm2-runtime", "dist/src/main.js"]
