FROM node:alpine

WORKDIR app

COPY ../../package.json .

COPY ../../yarn.lock .

RUN yarn install


COPY ../../. .

RUN npx prisma generate

RUN yarn build

VOLUME ["/app/dist"]

CMD ["node", "dist/src/main.js"]
